### ISSUE TITLE
Why reinvent the wheel?

### ISSUE THREAD

**Issue by agrueneberg** [ibl/cbio#1]
https://github.com/agrueneberg/CGDS-JS

**Comment by jonasalmeida** [comment]
Just for fun really - and also to explore an implementation that is as "server-less" as possible. Some elaboration on that: instead of having a node.js doing I/O and parsing (one would still have to deploy it somewhere), ibl/cbio relies of a **sharable server-side JS** hosted in Google Script (https://script.google.com/a/macros/mathbiol.org/d/17o5B1sXjmUEWRHG_6vHQhmz3qTMPCgpOvlX1kNvDQCkVcrH5ANsi2NrY/edit) that does only I/O. I am entranced by node.js like everybody else but not blind to the fact that it is still a server. You'll also notice with some displeasure that this experiment relies on JSONP instead of setting CORS in google script. That is also part of the exercise of making it as light on knowledge about the server as possible.
